import { useState } from "react";
import "../../styles/colorful-components.css";
import "../../styles/joyful-animations.css";

export default function BugReportGenerator() {
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [report, setReport] = useState(null);
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!description.trim()) {
      setError("Please enter a bug description");
      return;
    }

    setLoading(true);
    setError(null);
    setReport(null);

    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL || "http://localhost:4000"}/api/bugs/generate-report`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ plainTextDescription: description }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate report");
      }

      setReport(data.report);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!report) return;

    const formattedReport = `
═══════════════════════════════════════════════════════════════
                    PROFESSIONAL BUG REPORT                      
═══════════════════════════════════════════════════════════════

1. BUG ID
   ${report.bug_id}

2. TITLE
   ${report.title}

3. DESCRIPTION
   ${report.description}

4. STEPS TO REPRODUCE
${report.steps_to_reproduce.split('\n').map(line => '   ' + line).join('\n')}

5. ACTUAL OUTPUT
   ${report.actual_output}

6. EXPECTED OUTPUT
   ${report.expected_output}

7. PRIORITY
   ${report.priority}
   Justification: ${report.priority_justification}

8. SEVERITY
   ${report.severity}

9. ASSIGNEE
   ${report.assignee}

10. ENVIRONMENT
    ${report.environment}

═══════════════════════════════════════════════════════════════
Generated by AI Bug Report Generator
═══════════════════════════════════════════════════════════════
    `;

    navigator.clipboard.writeText(formattedReport.trim());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleReset = () => {
    setDescription("");
    setReport(null);
    setError(null);
  };

  return (
    <div className="bug-report-generator-container">
      <div className="generator-header">
        <h1 className="gradient-text">🤖 AI Bug Report Generator</h1>
        <p className="subtitle">Convert plain language descriptions into professional bug reports</p>
      </div>

      <div className="generator-content">
        {/* Input Section */}
        <div className="input-section card glass-card">
          <h2>📝 Describe Your Bug</h2>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Example: The login button doesn't work when I click it twice quickly. It shows an error message 'Invalid credentials' even though my password is correct..."
            className="bug-description-input"
            rows={8}
            disabled={loading}
          />

          <div className="button-group">
            <button
              onClick={handleGenerate}
              disabled={loading || !description.trim()}
              className="btn btn-primary generate-btn"
            >
              {loading ? (
                <>
                  <span className="spinner"></span>
                  Generating...
                </>
              ) : (
                <>
                  ✨ Generate Bug Report
                </>
              )}
            </button>

            {report && (
              <button onClick={handleReset} className="btn btn-secondary">
                🔄 Reset
              </button>
            )}
          </div>

          {error && (
            <div className="error-message">
              <span>⚠️ {error}</span>
            </div>
          )}
        </div>

        {/* Output Section */}
        {report && (
          <div className="output-section card glass-card fade-in">
            <div className="output-header">
              <h2>📋 Generated Bug Report</h2>
              <button onClick={handleCopy} className="btn btn-copy">
                {copied ? "✅ Copied!" : "📋 Copy to Clipboard"}
              </button>
            </div>

            <div className="bug-report-display">
              <div className="report-field">
                <label>1. Bug ID</label>
                <div className="field-value bug-id">{report.bug_id}</div>
              </div>

              <div className="report-field">
                <label>2. Title</label>
                <div className="field-value">{report.title}</div>
              </div>

              <div className="report-field">
                <label>3. Description</label>
                <div className="field-value">{report.description}</div>
              </div>

              <div className="report-field">
                <label>4. Steps to Reproduce</label>
                <div className="field-value steps">
                  {report.steps_to_reproduce.split('\n').map((step, idx) => (
                    <div key={idx} className="step-item">{step}</div>
                  ))}
                </div>
              </div>

              <div className="report-field">
                <label>5. Actual Output</label>
                <div className="field-value actual-output">{report.actual_output}</div>
              </div>

              <div className="report-field">
                <label>6. Expected Output</label>
                <div className="field-value expected-output">{report.expected_output}</div>
              </div>

              <div className="report-fields-grid">
                <div className="report-field">
                  <label>7. Priority</label>
                  <div className={`field-value priority priority-${report.priority.toLowerCase()}`}>
                    {report.priority}
                  </div>
                  <div className="field-justification">{report.priority_justification}</div>
                </div>

                <div className="report-field">
                  <label>8. Severity</label>
                  <div className={`field-value severity severity-${report.severity.toLowerCase()}`}>
                    {report.severity}
                  </div>
                </div>
              </div>

              <div className="report-fields-grid">
                <div className="report-field">
                  <label>9. Assignee</label>
                  <div className="field-value assignee">{report.assignee}</div>
                </div>

                <div className="report-field">
                  <label>10. Environment</label>
                  <div className="field-value environment">{report.environment}</div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      <style>{`
        .bug-report-generator-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 2rem;
          min-height: 100vh;
        }

        .generator-header {
          text-align: center;
          margin-bottom: 3rem;
        }

        .generator-header h1 {
          font-size: 2.5rem;
          margin-bottom: 0.5rem;
        }

        .subtitle {
          color: var(--text-secondary, #666);
          font-size: 1.1rem;
        }

        .generator-content {
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .card {
          background: white;
          border-radius: 16px;
          padding: 2rem;
          box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
        }

        .glass-card {
          backdrop-filter: blur(10px);
          background: rgba(255, 255, 255, 0.95);
          border: 1px solid rgba(255, 255, 255, 0.3);
        }

        .input-section h2,
        .output-section h2 {
          margin-bottom: 1.5rem;
          font-size: 1.5rem;
          color: var(--primary-color, #4a5cff);
        }

        .bug-description-input {
          width: 100%;
          padding: 1rem;
          border: 2px solid #e0e0e0;
          border-radius: 12px;
          font-size: 1rem;
          font-family: inherit;
          resize: vertical;
          transition: all 0.3s ease;
          background: #fafafa;
        }

        .bug-description-input:focus {
          outline: none;
          border-color: var(--primary-color, #4a5cff);
          background: white;
          box-shadow: 0 0 0 3px rgba(74, 92, 255, 0.1);
        }

        .bug-description-input:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .button-group {
          display: flex;
          gap: 1rem;
          margin-top: 1.5rem;
        }

        .btn {
          padding: 0.875rem 1.75rem;
          border: none;
          border-radius: 10px;
          font-size: 1rem;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.3s ease;
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
        }

        .btn-primary {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
        }

        .btn-primary:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 8px 20px rgba(102, 126, 234, 0.4);
        }

        .btn-primary:disabled {
          opacity: 0.6;
          cursor: not-allowed;
          transform: none;
        }

        .btn-secondary {
          background: #f0f0f0;
          color: #333;
        }

        .btn-secondary:hover {
          background: #e0e0e0;
        }

        .btn-copy {
          background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
          color: white;
          padding: 0.75rem 1.5rem;
        }

        .btn-copy:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 20px rgba(245, 87, 108, 0.4);
        }

        .spinner {
          display: inline-block;
          width: 16px;
          height: 16px;
          border: 2px solid rgba(255, 255, 255, 0.3);
          border-top-color: white;
          border-radius: 50%;
          animation: spin 0.6s linear infinite;
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        .error-message {
          margin-top: 1rem;
          padding: 1rem;
          background: #fee;
          border-left: 4px solid #f44;
          border-radius: 8px;
          color: #c00;
        }

        .output-section {
          animation: fadeInUp 0.5s ease;
        }

        @keyframes fadeInUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .output-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 2rem;
        }

        .bug-report-display {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .report-field {
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
        }

        .report-field label {
          font-weight: 700;
          color: #555;
          font-size: 0.9rem;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .field-value {
          padding: 1rem;
          background: #f8f9fa;
          border-radius: 8px;
          border-left: 4px solid var(--primary-color, #4a5cff);
          font-size: 1rem;
          line-height: 1.6;
        }

        .field-value.bug-id {
          font-family: 'Courier New', monospace;
          font-weight: bold;
          color: #764ba2;
          border-left-color: #764ba2;
        }

        .field-value.steps {
          padding: 0;
          background: transparent;
          border: none;
        }

        .step-item {
          padding: 0.75rem 1rem;
          background: #f8f9fa;
          border-radius: 8px;
          margin-bottom: 0.5rem;
          border-left: 4px solid #4a5cff;
        }

        .field-value.actual-output {
          background: #fff3f3;
          border-left-color: #f5576c;
          color: #c00;
        }

        .field-value.expected-output {
          background: #f0fff4;
          border-left-color: #48bb78;
          color: #2f855a;
        }

        .report-fields-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 1.5rem;
        }

        .field-value.priority,
        .field-value.severity {
          font-weight: bold;
          text-align: center;
          padding: 0.75rem;
        }

        .priority-blocker, .priority-critical { 
          background: #fee; 
          color: #c00; 
          border-left-color: #f00; 
        }
        .priority-high { 
          background: #fff3e0; 
          color: #e65100; 
          border-left-color: #ff9800; 
        }
        .priority-medium { 
          background: #fff9e0; 
          color: #f57f17; 
          border-left-color: #ffc107; 
        }
        .priority-low { 
          background: #f0fff4; 
          color: #2f855a; 
          border-left-color: #48bb78; 
        }

        .severity-critical { 
          background: #fee; 
          color: #c00; 
          border-left-color: #f00; 
        }
        .severity-major { 
          background: #fff3e0; 
          color: #e65100; 
          border-left-color: #ff9800; 
        }
        .severity-minor { 
          background: #fff9e0; 
          color: #f57f17; 
          border-left-color: #ffc107; 
        }
        .severity-trivial { 
          background: #f0f0f0; 
          color: #666; 
          border-left-color: #999; 
        }

        .field-justification {
          font-size: 0.9rem;
          color: #666;
          font-style: italic;
          padding: 0.5rem 1rem;
          background: #f8f9fa;
          border-radius: 6px;
          margin-top: 0.5rem;
        }

        .field-value.assignee,
        .field-value.environment {
          background: #e3f2fd;
          border-left-color: #2196f3;
          color: #1565c0;
          font-weight: 500;
        }

        @media (max-width: 768px) {
          .bug-report-generator-container {
            padding: 1rem;
          }

          .generator-header h1 {
            font-size: 2rem;
          }

          .report-fields-grid {
            grid-template-columns: 1fr;
          }

          .output-header {
            flex-direction: column;
            align-items: flex-start;
            gap: 1rem;
          }
        }
      `}</style>
    </div>
  );
}
